# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
 database: nested_form_cocoon_ex_development
 adapter: postgresql
 username: postgres
 password: 12345678
 host: localhost

